export {default as Home} from '../pages/Home/Home';
export {default as Error} from '../pages/Error/Error';
export {default as Login} from '../pages/Login/Login';
export {default as Signup} from '../pages/Signup/Singup';
export {default as Crypto} from '../pages/Crypto/Crypto';
export {default as Blog} from './Blog/Blog';
export {default as BlogDetails} from './BlogDetails/BlogDetails';
export {default as SubmitBlog} from '../pages/SubmitBlog/SubmitBlog';
export {default as UpdateBlog} from '../pages/UpdateBlog/UpdateBlog';